apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: infra-tools
spec:
  project: default
  destination:
    namespace: application
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.4.0        # <- версия чарта из Chart.yaml
    helm:
      values: |
        mode: standalone        # для учебки достаточно
        rootUser: minio
        rootPassword: minio123
        buckets:
          - name: mlflow-artifacts
            policy: none
            purge: false
        persistence:
          enabled: false
        service:
          type: ClusterIP
        resources:
          requests:
            memory: 512Mi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
